version: "2"
linters:
  default: all
  disable:
  - cyclop
  - depguard
  - dupl
  - exhaustruct
  - funcorder
  - funlen
  - godox
  - lll
  - perfsprint
  - recvcheck
  - revive
  - wrapcheck
  - wsl
  settings:
    varnamelen:
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
