# golangci-lint run --print-issued-lines=false --uniq-by-line=false --no-config --enable-all 2> /dev/null | awk 'NF>1{print $NF}' | tr -d '()' | sort -u
linters:
  enable-all: true
  disable:
  - depguard
  - cyclop
  - dupl
  - exhaustivestruct
  - exhaustruct
  - funlen
  - godot
  - godox
  - gofumpt
  - ireturn
  - lll
  - nlreturn
  - prealloc
  - revive
  - tagliatelle
  - varnamelen
  - wrapcheck
  - wsl
