name: CI

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    # - edited
    branches:
    - main

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
    - name: Pull
      run: make -j pull
    - name: Lint
      run: make lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version-file: .go-version
        cache: true
    - name: Download dependencies
      run: go mod download
    - name: Build
      run: go build -v .

  docs:
    name: Test Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version-file: .go-version
        cache: true
    - name: Download dependencies
      run: go mod download
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
    - name: Generate and validate docs
      run: make docs test/docs
    - name: Check docs
      run: |
        GIT_STATUS=$(git status --porcelain)
        test -z "$GIT_STATUS" || (echo -e "Unexpected difference after code generation: $GIT_STATUS"; exit 1)

  test:
    name: Test
    needs:
    - lint
    - build
    - docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform:
        - 1.8.*
        - 1.9.*
        - 1.10.*
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version-file: .go-version
        cache: true
    - name: Download dependencies
      run: go mod download
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ matrix.terraform }}
        terraform_wrapper: false
    - name: Test
      run: make test/pkg test/acc

  check:
    name: Test
    runs-on: ubuntu-latest
    if: always()
    needs:
    - test
    steps:
    - run: exit 1
      # see https://stackoverflow.com/a/67532120/4907315
      if: >-
        ${{
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled')
        }}
