name: CI

on: # yamllint disable-line rule:truthy
  push:
    branches:
    - main
    paths-ignore:
    - README.md
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    # - edited
    branches:
    - main
    paths-ignore:
    - README.md

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version-file: .go-version
        cache: true
    - name: Download dependencies
      run: go mod download
    - name: Build
      run: go build -v .
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

  docs:
    name: Test Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version-file: .go-version
        cache: true
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    - name: Generate docs
      run: make docs
    - name: Check docs
      run: |
        GIT_STATUS=$(git status --porcelain)
        test -z "$GIT_STATUS" || (echo -e "Unexpected difference after code generation: $GIT_STATUS"; exit 1)

  test:
    name: Test
    needs:
    - build
    - docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform:
        - 1.3.*
        - 1.4.*
        - 1.5.*
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version-file: .go-version
        cache: true
    - name: Download dependencies
      run: go mod download
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ matrix.terraform }}
        terraform_wrapper: false
    - name: Test
      run: make test

  check:
    name: Test
    runs-on: ubuntu-latest
    if: always()
    needs:
    - test
    steps:
    - run: exit 1
      # see https://stackoverflow.com/a/67532120/4907315
      if: >-
        ${{
              contains(needs.*.result, 'failure')
          || contains(needs.*.result, 'cancelled')
        }}
