name: Release

on: # yamllint disable-line rule:truthy
  push:
    tags:
    - v*

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # environment: release
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Fetch tags
      run: git fetch --force --tags
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version-file: .go-version
        cache: true
    - name: Import GPG key
      id: gpg
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_FINGERPRINT: ${{ steps.gpg.outputs.fingerprint }}
